export const minterContractAddress =
  'erd1qqqqqqqqqqqqqpgqgcls0ehlw2ukhyzv8yk6tqmwu00sncxshn9qkaxdeu'
export const dataContractAddress =
  'erd1qqqqqqqqqqqqqpgq2uh3aknjmk33ydczkppnnredhs0jz5rphn9qq3xjuw'
export const marketContractAddress =
  'erd1qqqqqqqqqqqqqpgqps7kmy5rlflx8gwjz3hmnlnuxjyhvleshn9quq48ra'
